Fix SUPERSTITION mode: replace _make_search_date with common.get_search_date_range
- Fixed AttributeError: 'Lotto645' object has no attribute '_make_search_date'
- The _make_search_date method was moved to common.py as get_search_date_range
- Updated get_my_last_week_numbers to use common.get_search_date_range()